name: Deploy PHP Sample Site

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate PHP Syntax
        run: find . -name "*.php" -print0 | xargs -0 -n1 php -l

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Convert PHP to Static HTML (Optional)
        run: |
          mkdir output
          rsync -av --exclude='output' ./ output/
          # Use PHP to render dynamic pages into static HTML (if needed)
          # Example: php script.php > output/index.html
          # Remove PHP files if they shouldn't be part of the output
          find output -name "index.php" -exec rm {} \;

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: output
